### PR TITLE
Apply rubocop

### PR DESCRIPTION
**Pull request by mccalluc**
Is there a base configuration / profile that we'd like to use across projects? Consistency is good... but the config in pdc_describe has lots of details that are particular to that project that I wouldn't want to just copy over.

### CODE REVIEW

**Comment by carolyncole** [comment]
This would be what I would lean towards (https://github.com/pulibrary/rails-template/blob/main/.rubocop.yml), but as we said this morning lets keep things simple.

**Comment by mccalluc** [comment]
Thanks! I'll convert this to draft, apply that config, and update the PR.

I'm not sure what keeping things simple means in this case -- If it's just not to worry about rubocop at this point, then we're making PR reviews less simple -- Or maybe it's something else that should be simplified?

**Comment by jrgriffiniii** [comment]
I hope that no one objects, however, I have attempted to advance this work with https://github.com/pulibrary/tiger-data/pull/21 (this was just to ensure that I can then proceed with features and tests without violating any RuboCop style guidelines). https://github.com/pulibrary/tiger-data/pull/21 should deprecate this, however, I defer to @mccalluc, @carolyncole, and all other colleagues please.

**Comment by mccalluc** [comment]
Replaced by #34

**Pull request closed without merging**
